export interface CauseItem { label: string; pct: number }
export interface MortalityDetail {
  headline: string;
  causes: CauseItem[];
  context: string;
  trend: string;
}
export interface CountryAnalysis {
  slug: string;
  childMortality: MortalityDetail;
  maternalMortality: MortalityDetail;
  drivers: string[];
  sdgNote: string;
}

export const ANALYSIS: Record<string, CountryAnalysis> = {
  afghanistan: {
    slug: "afghanistan",
    childMortality: {
      headline: "Afghanistan has one of the highest under-5 mortality rates in the world at 101.3 per 1,000 — roughly 1 in 10 children dies before their fifth birthday.",
      causes: [
        { label: "Neonatal complications", pct: 28 },
        { label: "Pneumonia & ARI", pct: 22 },
        { label: "Malnutrition", pct: 18 },
        { label: "Diarrhoeal diseases", pct: 14 },
        { label: "Other preventable", pct: 18 },
      ],
      context: "Decades of conflict have destroyed healthcare infrastructure. Only 38% of health facilities are fully functional, and fewer than 30% of births occur in a health facility. Children in rural provinces face mortality rates 3× higher than urban centres.",
      trend: "Progress between 2002–2019 has reversed since 2021 under the new administration, with international health funding largely withdrawn.",
    },
    maternalMortality: {
      headline: "620 maternal deaths per 100,000 live births — one mother dies every 1.4 hours. Afghanistan is among the most dangerous places on Earth to give birth.",
      causes: [
        { label: "Severe haemorrhage", pct: 27 },
        { label: "Pre-eclampsia / eclampsia", pct: 22 },
        { label: "Sepsis & infection", pct: 16 },
        { label: "Obstructed labour", pct: 14 },
        { label: "Unsafe abortion", pct: 12 },
        { label: "Other complications", pct: 9 },
      ],
      context: "Only 21% of births are attended by a skilled health professional. Under current governance, women face severe restrictions on accessing healthcare without a male guardian, and female healthcare workers have been largely barred from hospitals.",
      trend: "The ratio fell from over 1,800 in 2000 to ~620 by 2023, but progress has stalled entirely. WHO warns of reversal without sustained access.",
    },
    drivers: [
      "Ongoing armed conflict destroying health facilities",
      "Severe restriction of women's rights and healthcare access",
      "Critical shortage of trained female health workers",
      "Extreme poverty — 97% of population below poverty line (2022)",
      "Widespread food insecurity and acute malnutrition",
      "Withdrawal of international aid and NGO operations",
    ],
    sdgNote: "Afghanistan is off-track for all SDG 3 targets. At current rates it will not reach ≤25 child deaths per 1,000 before 2070.",
  },
  mali: {
    slug: "mali",
    childMortality: {
      headline: "Mali is the second deadliest country for children with 97.1 per 1,000 under-5 mortality — around 116,000 child deaths per year.",
      causes: [
        { label: "Malaria", pct: 30 },
        { label: "Neonatal complications", pct: 25 },
        { label: "Pneumonia", pct: 16 },
        { label: "Diarrheal diseases", pct: 13 },
        { label: "Other", pct: 16 },
      ],
      context: "Mali sits in the Sahel where climate change, desertification and conflict devastate child health. Malaria kills ~35,000 children under five per year. The rainy season drives deadly spikes in both malaria and diarrhoeal disease.",
      trend: "Progress of ~45% reduction between 2000–2015 has reversed since 2012 due to political instability and jihadist violence.",
    },
    maternalMortality: {
      headline: "440 maternal deaths per 100,000. With a fertility rate of 5.8, the lifetime risk of maternal death for a Malian woman is approximately 1 in 38.",
      causes: [
        { label: "Haemorrhage", pct: 30 },
        { label: "Hypertensive disorders", pct: 20 },
        { label: "Sepsis", pct: 18 },
        { label: "Obstructed labour", pct: 15 },
        { label: "Malaria in pregnancy", pct: 10 },
        { label: "Other", pct: 7 },
      ],
      context: "Only 43% of births occur in health facilities. Northern Mali has been under jihadist control intermittently since 2012, leaving entire regions without functioning maternity care.",
      trend: "Improved ~40% between 2000–2017 but stagnated since the intensification of the Sahel security crisis.",
    },
    drivers: [
      "Three coups since 2012 — chronic political instability",
      "Jihadist violence destroying health facilities in the north",
      "Climate shocks — drought and flooding disrupting food supply",
      "High fertility rate (5.8) stressing maternal health systems",
      "Low female education and early marriage (child bride rate ~52%)",
    ],
    sdgNote: "Mali will not reach SDG child mortality targets until well after 2050 without major intervention.",
  },
  somalia: {
    slug: "somalia",
    childMortality: {
      headline: "Somalia's under-5 mortality of 93.0 per 1,000 reflects decades of state collapse leaving health infrastructure almost nonexistent.",
      causes: [
        { label: "Neonatal causes", pct: 29 },
        { label: "Pneumonia", pct: 20 },
        { label: "Diarrheal diseases", pct: 17 },
        { label: "Measles & vaccine-preventable", pct: 10 },
        { label: "Malaria", pct: 9 },
        { label: "Other", pct: 15 },
      ],
      context: "Somalia has experienced continuous civil war since 1991 with no functioning national health system. Vaccination coverage is below 30% nationally. 1 in 5 Somali children is acutely malnourished.",
      trend: "Limited progress from a very high baseline. Pockets of improvement exist in Mogadishu and Somaliland.",
    },
    maternalMortality: {
      headline: "621 maternal deaths per 100,000 — a Somali woman faces a 1 in 22 lifetime risk of dying from pregnancy-related causes.",
      causes: [
        { label: "Haemorrhage", pct: 31 },
        { label: "Obstructed labour / fistula", pct: 19 },
        { label: "Sepsis", pct: 18 },
        { label: "Eclampsia", pct: 15 },
        { label: "Unsafe abortion", pct: 9 },
        { label: "Other", pct: 8 },
      ],
      context: "Only 9% of births are attended by a skilled birth attendant — one of the lowest rates globally. FGM prevalence is ~98%, contributing to obstructed labour and fistula. Al-Shabaab actively restricts health services.",
      trend: "Minimal improvement over the past decade. International NGOs provide the majority of maternal health services.",
    },
    drivers: [
      "Continuous armed conflict since 1991",
      "Near-complete collapse of the state health system",
      "Near-universal FGM (98%) causing obstetric complications",
      "2.9 million internally displaced persons",
      "Al-Shabaab restricting health worker access",
    ],
    sdgNote: "Rebuilding Somalia's health infrastructure requires sustained peace and a decade of intensive investment.",
  },
  "central-african-rep": {
    slug: "central-african-rep",
    childMortality: {
      headline: "CAR's under-5 mortality of 92.2 per 1,000 reflects a country where two-thirds of territory is outside government control.",
      causes: [
        { label: "Malaria", pct: 28 },
        { label: "Neonatal causes", pct: 24 },
        { label: "Respiratory infections", pct: 18 },
        { label: "Diarrhoea", pct: 14 },
        { label: "Other", pct: 16 },
      ],
      context: "CAR ranks last or near-last on the Human Development Index. Armed groups control large portions of the country. Malaria is hyperendemic and responsible for ~1 in 4 child deaths.",
      trend: "Progress made in the 2000s has been reversed by ongoing conflict since 2013.",
    },
    maternalMortality: {
      headline: "835 maternal deaths per 100,000 — one of the three highest rates in the world. A woman in CAR faces a 1 in 17 lifetime risk of dying from pregnancy complications.",
      causes: [
        { label: "Haemorrhage", pct: 34 },
        { label: "Infection / sepsis", pct: 22 },
        { label: "Eclampsia", pct: 17 },
        { label: "Obstructed labour", pct: 13 },
        { label: "Unsafe abortion", pct: 8 },
        { label: "Other", pct: 6 },
      ],
      context: "Only 40% of births are attended by skilled personnel. Many facilities have been looted or destroyed by armed groups. MSF operates key facilities under constant security constraints.",
      trend: "Almost no improvement in 15 years due to perpetual conflict.",
    },
    drivers: [
      "Ongoing multi-faction civil conflict since 2013",
      "Only 1 doctor per 20,000 people",
      "Widespread looting and destruction of health facilities",
      "Extreme poverty (80%+ below $1.90/day)",
      "Limited road infrastructure — large areas inaccessible in rainy season",
    ],
    sdgNote: "CAR will not achieve SDG 3 targets this century without a fundamental change in security and governance.",
  },
  chad: {
    slug: "chad",
    childMortality: {
      headline: "Chad's under-5 mortality rate of 89.3 per 1,000 comes alongside the world's highest maternal mortality ratio at 1,063 per 100,000.",
      causes: [
        { label: "Malaria", pct: 26 },
        { label: "Neonatal causes", pct: 26 },
        { label: "Diarrhoeal disease", pct: 15 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 20 },
      ],
      context: "Chad hosts over 600,000 refugees from Sudan and CAR, placing catastrophic pressure on health systems. Sahel location means extreme heat, recurring drought, and seasonal flooding.",
      trend: "Child mortality improved ~45% since 2000 but the pace has slowed since 2015.",
    },
    maternalMortality: {
      headline: "Chad has the world's highest maternal mortality at 1,063 per 100,000 — roughly 1 in 15 women will die from pregnancy-related causes.",
      causes: [
        { label: "Haemorrhage", pct: 36 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 16 },
        { label: "Obstructed labour", pct: 14 },
        { label: "Anaemia", pct: 8 },
        { label: "Other", pct: 5 },
      ],
      context: "Fewer than 500 doctors for 18 million people. Only 22% of births are attended by skilled health workers. Child marriage rate is among the world's highest — driving dangerous teenage pregnancies.",
      trend: "Improved from ~1,700 in 2000 to ~1,063 today, but remains the world's worst. Will not reach SDG target before 2150.",
    },
    drivers: [
      "World's highest child marriage rate — 52% of girls married before 18",
      "Severe shortage of health workers",
      "Hosting 600,000+ refugees straining health infrastructure",
      "Recurring drought and flooding in Sahel",
      "Only 22% skilled birth attendance",
    ],
    sdgNote: "Chad faces the largest absolute gap to SDG maternal mortality targets of any country on Earth.",
  },
  "sierra-leone": {
    slug: "sierra-leone",
    childMortality: {
      headline: "Sierra Leone's under-5 mortality of 87.2 per 1,000 is the legacy of civil war (1991–2002) and the 2014–2016 Ebola epidemic.",
      causes: [
        { label: "Malaria", pct: 31 },
        { label: "Neonatal causes", pct: 27 },
        { label: "Pneumonia", pct: 14 },
        { label: "Diarrhoea", pct: 12 },
        { label: "Other", pct: 16 },
      ],
      context: "The 2014–16 Ebola crisis killed 14,000+ Sierra Leoneans and decimated an already fragile health system. Community distrust of health facilities continues to suppress care-seeking behaviour.",
      trend: "Meaningful progress — from 240 per 1,000 in 2000 to 87 today — but plateaued post-Ebola.",
    },
    maternalMortality: {
      headline: "443 maternal deaths per 100,000 — among the most dangerous places in the world to give birth.",
      causes: [
        { label: "Haemorrhage", pct: 28 },
        { label: "Eclampsia", pct: 22 },
        { label: "Sepsis", pct: 19 },
        { label: "Obstructed labour", pct: 16 },
        { label: "Malaria in pregnancy", pct: 9 },
        { label: "Other", pct: 6 },
      ],
      context: "The Free Healthcare Initiative (2010) improved access but was overwhelmed by demand. The 2014 Ebola crisis forced closure of many facilities during a critical window.",
      trend: "Improved from ~2,200 in 2000 to ~443 today — substantial reduction — but still critically high.",
    },
    drivers: [
      "11-year civil war destroying health infrastructure",
      "2014–2016 Ebola epidemic devastating remaining health systems",
      "High teenage pregnancy rate (28% of births to mothers under 18)",
      "Seasonal flooding disrupting health facility access",
      "Community distrust of formal health systems post-Ebola",
    ],
    sdgNote: "Sierra Leone is on a positive trajectory but will not meet SDG targets without sustained investment.",
  },
  niger: {
    slug: "niger",
    childMortality: {
      headline: "Niger's under-5 mortality of 82.0 per 1,000 affects the country with the world's highest total fertility rate — 6.9 children per woman.",
      causes: [
        { label: "Malaria", pct: 27 },
        { label: "Neonatal causes", pct: 25 },
        { label: "Diarrhoea", pct: 16 },
        { label: "Pneumonia", pct: 14 },
        { label: "Other", pct: 18 },
      ],
      context: "Niger is the world's poorest country by GDP per capita. Malnutrition affects over 40% of children under five — one of the highest rates globally. Population is growing faster than health systems can expand.",
      trend: "Significant reductions 2000–2015 driven by malaria net distribution and ORS programmes. Progress stalled since 2019.",
    },
    maternalMortality: {
      headline: "441 maternal deaths per 100,000. With a fertility rate of 6.9, the cumulative lifetime risk of maternal death reaches 1 in 25.",
      causes: [
        { label: "Haemorrhage", pct: 29 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 17 },
        { label: "Obstructed labour", pct: 15 },
        { label: "Anaemia", pct: 10 },
        { label: "Other", pct: 8 },
      ],
      context: "Child marriage is virtually universal in parts of Niger — 76% of girls marry before 18. Early and closely-spaced pregnancies are major drivers of maternal death.",
      trend: "Modest improvement, but the absolute number of maternal deaths is rising because population growth outpaces the falling mortality rate.",
    },
    drivers: [
      "World's highest fertility rate (6.9)",
      "World's highest child marriage rate — 76% before age 18",
      "Extreme poverty — lowest GDP per capita globally",
      "Sahel climate shocks causing recurring food crises",
      "Jihadist expansion from Mali destabilising health access",
    ],
    sdgNote: "Niger's combination of very high fertility and poverty makes it the most structurally challenged country for SDG 3 health targets.",
  },
  guinea: {
    slug: "guinea",
    childMortality: {
      headline: "Guinea's under-5 mortality of 79.5 per 1,000 sits in a country that was the epicentre of the 2014 West African Ebola outbreak.",
      causes: [
        { label: "Malaria", pct: 29 },
        { label: "Neonatal causes", pct: 24 },
        { label: "Diarrhoea", pct: 15 },
        { label: "Pneumonia", pct: 14 },
        { label: "Other", pct: 18 },
      ],
      context: "Guinea was ground zero for the 2014 Ebola epidemic, which exposed and amplified systemic health weaknesses. Malaria is responsible for more child deaths than any other cause, yet bed net coverage remains below 50% nationally.",
      trend: "Progress since 2000 disrupted by political crises (coup 2021) and epidemic setbacks.",
    },
    maternalMortality: {
      headline: "553 maternal deaths per 100,000 driven by a severe shortage of skilled birth attendants and widespread early marriage.",
      causes: [
        { label: "Haemorrhage", pct: 30 },
        { label: "Sepsis", pct: 20 },
        { label: "Eclampsia", pct: 19 },
        { label: "Obstructed labour", pct: 15 },
        { label: "Anaemia", pct: 9 },
        { label: "Other", pct: 7 },
      ],
      context: "FGM prevalence exceeds 94% in Guinea, contributing to obstructed labour and maternal death. Only 45% of births are attended by skilled health workers. The 2021 military coup disrupted international health aid.",
      trend: "Moderate improvement since 2000 but stalled after the 2021 coup.",
    },
    drivers: [
      "94%+ FGM prevalence driving obstetric complications",
      "2014 Ebola epidemic — lasting health system damage",
      "Military coup 2021 reducing international support",
      "High child marriage rate (52% before age 18)",
      "Severe shortage of female health workers outside Conakry",
    ],
    sdgNote: "Guinea needs sustained peace and governance reform to accelerate the health improvements seen in the early 2000s.",
  },
  "south-sudan": {
    slug: "south-sudan",
    childMortality: {
      headline: "South Sudan — the world's youngest nation — has under-5 mortality of 78.1 per 1,000 and the world's second highest maternal mortality at 1,223 per 100,000.",
      causes: [
        { label: "Neonatal causes", pct: 27 },
        { label: "Malaria", pct: 24 },
        { label: "Acute malnutrition", pct: 20 },
        { label: "Diarrhoea", pct: 16 },
        { label: "Other", pct: 13 },
      ],
      context: "South Sudan has been in civil war since 2013. Over 4 million people are displaced. 70% of health facilities have been looted, damaged or destroyed.",
      trend: "South Sudan has never had a robust health baseline — it became independent in 2011 and immediately entered conflict.",
    },
    maternalMortality: {
      headline: "1,223 maternal deaths per 100,000 — the second highest in the world. A South Sudanese woman has a 1 in 7 lifetime chance of dying from pregnancy-related causes.",
      causes: [
        { label: "Haemorrhage", pct: 32 },
        { label: "Sepsis", pct: 24 },
        { label: "Eclampsia", pct: 18 },
        { label: "Obstructed labour", pct: 14 },
        { label: "Malaria in pregnancy", pct: 7 },
        { label: "Other", pct: 5 },
      ],
      context: "Only 19% of births are attended by skilled health workers. Civil war has driven female health professionals out of the country. MSF and IRC are effectively the primary maternal health providers in conflict-affected states.",
      trend: "Among the worst rates ever recorded globally. Conditions are deteriorating.",
    },
    drivers: [
      "Ongoing civil war — fighting between government and rebel factions",
      "70% of health facilities damaged or destroyed",
      "4M+ displaced people",
      "Near-complete collapse of the health workforce",
      "7 million facing starvation (2023)",
    ],
    sdgNote: "South Sudan faces a humanitarian catastrophe that makes SDG progress meaningless without first achieving lasting peace.",
  },
  nigeria: {
    slug: "nigeria",
    childMortality: {
      headline: "Nigeria has under-5 mortality of 74.2 per 1,000 — and because of its population of 220M, it accounts for more child deaths in absolute numbers than any other country on Earth.",
      causes: [
        { label: "Neonatal causes", pct: 30 },
        { label: "Malaria", pct: 28 },
        { label: "Pneumonia", pct: 14 },
        { label: "Diarrhoea", pct: 12 },
        { label: "Other", pct: 16 },
      ],
      context: "Nigeria accounts for ~800,000 child deaths per year — nearly 1 in 6 of all global child deaths. North-west and north-east regions have mortality rates 2–3× the national average. Boko Haram insurgency has destroyed health facilities serving millions.",
      trend: "Nigeria has made slower progress than comparable sub-Saharan African countries. Federal structure creates extreme regional variation.",
    },
    maternalMortality: {
      headline: "1,047 maternal deaths per 100,000 — Nigeria accounts for approximately 20% of all global maternal deaths despite having 3% of the world's population.",
      causes: [
        { label: "Haemorrhage", pct: 32 },
        { label: "Eclampsia / hypertension", pct: 21 },
        { label: "Sepsis", pct: 16 },
        { label: "Obstructed labour", pct: 13 },
        { label: "Unsafe abortion", pct: 11 },
        { label: "Other", pct: 7 },
      ],
      context: "Nigeria is oil-rich but spends only ~4% of GDP on health vs the AU target of 15%. The north-east Boko Haram crisis has displaced millions. Unsafe abortion — illegal in most circumstances — is a significant contributor.",
      trend: "Slow and uneven. Absolute numbers of maternal deaths may be increasing as population grows faster than mortality falls.",
    },
    drivers: [
      "Accounts for ~20% of all global maternal deaths",
      "Boko Haram insurgency destroying health facilities in the north-east",
      "Chronic health underfunding (4% of GDP)",
      "Extreme regional inequality in health access",
      "High adolescent pregnancy rate (23%)",
    ],
    sdgNote: "Nigeria alone could derail global SDG 3 progress. Targeted investment in the north-east and north-west is critical.",
  },
  "guinea-bissau": {
    slug: "guinea-bissau",
    childMortality: {
      headline: "Guinea-Bissau's under-5 mortality of 71.7 per 1,000 reflects one of West Africa's most politically unstable nations with nine coups since 1974.",
      causes: [
        { label: "Malaria", pct: 32 },
        { label: "Neonatal causes", pct: 23 },
        { label: "Diarrhoea", pct: 15 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 17 },
      ],
      context: "Political instability has made sustained health investment virtually impossible. Malaria is responsible for nearly a third of all child deaths.",
      trend: "Modest improvement correlated with periods of political stability and external aid.",
    },
    maternalMortality: {
      headline: "725 maternal deaths per 100,000 — one of the highest in West Africa, driven by a critical shortage of skilled birth attendants.",
      causes: [
        { label: "Haemorrhage", pct: 29 },
        { label: "Eclampsia", pct: 22 },
        { label: "Sepsis", pct: 18 },
        { label: "Obstructed labour", pct: 16 },
        { label: "Other", pct: 15 },
      ],
      context: "Only 45% of births are attended by skilled professionals. Drug trafficking through Guinea-Bissau has corrupted governance and diverted resources away from social services.",
      trend: "Limited progress. Drug trade economy has entrenched governance failure.",
    },
    drivers: [
      "Nine coups since 1974 — chronic political instability",
      "West Africa's main drug trafficking hub",
      "Near-complete aid dependency for health services",
      "Critical shortage of health professionals",
      "High malaria burden throughout the year",
    ],
    sdgNote: "Guinea-Bissau's political economy is the primary obstacle to SDG progress.",
  },
  lesotho: {
    slug: "lesotho",
    childMortality: {
      headline: "Lesotho's under-5 mortality of 70.1 per 1,000 is heavily influenced by the world's second highest HIV/AIDS prevalence (23% of adults).",
      causes: [
        { label: "Neonatal causes", pct: 28 },
        { label: "HIV/AIDS-related", pct: 22 },
        { label: "Pneumonia", pct: 17 },
        { label: "Diarrhoea", pct: 13 },
        { label: "Other", pct: 20 },
      ],
      context: "HIV/AIDS is the single largest driver of excess child and maternal mortality. PMTCT programmes have reduced vertical HIV transmission but it remains significant.",
      trend: "Improved significantly thanks to HIV treatment scale-up.",
    },
    maternalMortality: {
      headline: "566 maternal deaths per 100,000 — disproportionately driven by HIV/AIDS in pregnancy and the world's highest per-capita tuberculosis burden.",
      causes: [
        { label: "HIV/AIDS in pregnancy", pct: 30 },
        { label: "Haemorrhage", pct: 22 },
        { label: "Tuberculosis", pct: 15 },
        { label: "Eclampsia", pct: 15 },
        { label: "Sepsis", pct: 12 },
        { label: "Other", pct: 6 },
      ],
      context: "Lesotho has the world's highest TB incidence per capita. The HIV-TB co-epidemic is devastating for pregnant women. Mountainous terrain makes health facility access extremely difficult in winter.",
      trend: "Improved with ARV scale-up but remains high due to the dual HIV-TB burden.",
    },
    drivers: [
      "World's second highest HIV prevalence (23% of adults)",
      "World's highest TB incidence per capita",
      "Mountainous terrain isolating communities from health facilities",
      "Gender-based violence correlated with HIV transmission",
    ],
    sdgNote: "Lesotho's progress is tied to sustaining ARV supply chains. PEPFAR funding is critical.",
  },
  mozambique: {
    slug: "mozambique",
    childMortality: {
      headline: "Mozambique's under-5 mortality of 67.8 per 1,000 is worsening as two cyclones (Idai, Kenneth 2019) and a jihadist insurgency in the north compound structural challenges.",
      causes: [
        { label: "Malaria", pct: 28 },
        { label: "Neonatal causes", pct: 25 },
        { label: "Pneumonia", pct: 14 },
        { label: "Diarrhoea", pct: 13 },
        { label: "HIV/AIDS", pct: 8 },
        { label: "Other", pct: 12 },
      ],
      context: "Cyclone Idai (2019) was one of the worst tropical cyclones to hit Africa, destroying health facilities in Sofala province. The Cabo Delgado insurgency has displaced 1 million people in the north.",
      trend: "Strong progress 2000–2015 (~50% reduction) but climate shocks and conflict have reversed gains in affected regions.",
    },
    maternalMortality: {
      headline: "330 maternal deaths per 100,000 — still 15× the SDG target, driven by malaria in pregnancy and a critical shortage of health workers.",
      causes: [
        { label: "Haemorrhage", pct: 27 },
        { label: "Malaria in pregnancy", pct: 20 },
        { label: "Eclampsia", pct: 18 },
        { label: "Sepsis", pct: 16 },
        { label: "HIV in pregnancy", pct: 10 },
        { label: "Other", pct: 9 },
      ],
      context: "Debt crisis (2016), cyclones (2019), COVID-19, and the Cabo Delgado insurgency have severely disrupted momentum from the 2000s.",
      trend: "Improving trajectory disrupted by overlapping crises.",
    },
    drivers: [
      "Cyclone Idai (2019) devastating health infrastructure",
      "Cabo Delgado jihadist insurgency displacing 1M+",
      "Debt crisis (2016) cutting social spending",
      "12.5% HIV prevalence driving maternal deaths",
      "Only 0.07 doctors per 1,000 people",
    ],
    sdgNote: "Mozambique's trajectory was Africa's most promising; multiple overlapping crises now threaten to reverse two decades of gains.",
  },
  "burkina-faso": {
    slug: "burkina-faso",
    childMortality: {
      headline: "Burkina Faso's under-5 mortality of 66.9 per 1,000 is rapidly worsening as jihadist violence expands to cover 40% of the country.",
      causes: [
        { label: "Malaria", pct: 30 },
        { label: "Neonatal causes", pct: 23 },
        { label: "Diarrhoea", pct: 15 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 19 },
      ],
      context: "Two coups in 2022 and jihadist violence have created the worst humanitarian crisis in West Africa. Over 2 million are internally displaced. Jihadist groups have deliberately targeted health workers.",
      trend: "Progress made through 2015 is being rapidly reversed. Health workers are fleeing insecure areas.",
    },
    maternalMortality: {
      headline: "370 maternal deaths per 100,000 — rising rapidly as skilled birth attendants flee conflict zones.",
      causes: [
        { label: "Haemorrhage", pct: 28 },
        { label: "Eclampsia", pct: 20 },
        { label: "Sepsis", pct: 18 },
        { label: "Obstructed labour", pct: 16 },
        { label: "Anaemia", pct: 10 },
        { label: "Other", pct: 8 },
      ],
      context: "Two coups in 2022 led to expulsion of key NGOs. Health workers in the north and east receive death threats from jihadist groups.",
      trend: "Deteriorating rapidly since 2021. UN OCHA warns of humanitarian catastrophe.",
    },
    drivers: [
      "Two military coups (2022) expelling French forces and NGOs",
      "Jihadist groups controlling 40% of territory",
      "2M+ internally displaced persons",
      "Deliberate targeting of health workers and facilities",
      "4.7M facing acute food insecurity",
    ],
    sdgNote: "Without security stabilisation, all SDG targets in Burkina Faso are unreachable.",
  },
  angola: {
    slug: "angola",
    childMortality: {
      headline: "Angola's under-5 mortality of 65.7 per 1,000 is paradoxically high for an oil-rich country — the product of extreme inequality and 27 years of civil war (1975–2002).",
      causes: [
        { label: "Malaria", pct: 28 },
        { label: "Neonatal causes", pct: 26 },
        { label: "Diarrhoea", pct: 14 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 19 },
      ],
      context: "The civil war left vast areas contaminated with landmines and without health infrastructure. A 2018 measles outbreak killed over 1,000 children despite oil revenues funding government operations.",
      trend: "Significant improvement since peace in 2002 — mortality fell from ~250 per 1,000. Progress has slowed since 2015.",
    },
    maternalMortality: {
      headline: "340 maternal deaths per 100,000 — despite being one of Africa's largest oil exporters, health spending per capita remains critically low.",
      causes: [
        { label: "Haemorrhage", pct: 28 },
        { label: "Sepsis", pct: 20 },
        { label: "Eclampsia", pct: 18 },
        { label: "Malaria in pregnancy", pct: 15 },
        { label: "Obstructed labour", pct: 12 },
        { label: "Other", pct: 7 },
      ],
      context: "Angola's health system is profoundly unequal — Luanda has relatively modern facilities while rural provinces have minimal services. Oil price volatility causes repeated health budget cuts.",
      trend: "Post-war improvements concentrated in urban areas. Rural-urban inequality is widening.",
    },
    drivers: [
      "27-year civil war leaving landmines and destroyed infrastructure",
      "Oil wealth concentrated in Luanda elite",
      "Oil price volatility causing unpredictable health budget cycles",
      "Rural areas effectively unserved by formal health system",
      "2018 measles outbreak killing 1,000+ children",
    ],
    sdgNote: "Angola has the financial resources to dramatically accelerate progress — political will and equitable distribution are the core challenges.",
  },
  benin: {
    slug: "benin",
    childMortality: {
      headline: "Benin's under-5 mortality of 64.7 per 1,000 reflects moderate progress in one of West Africa's most stable democracies.",
      causes: [
        { label: "Malaria", pct: 29 },
        { label: "Neonatal causes", pct: 24 },
        { label: "Diarrhoea", pct: 15 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 19 },
      ],
      context: "Benin is one of few stable democracies in West Africa, enabling more consistent health investment. However, jihadist spillover from Burkina Faso is threatening the north.",
      trend: "Steady improvement — child mortality has halved since 2000. Political stability is the key differentiator from neighbours.",
    },
    maternalMortality: {
      headline: "523 maternal deaths per 100,000. Benin's 77% skilled birth attendance is relatively high for the region but complications management remains inadequate.",
      causes: [
        { label: "Haemorrhage", pct: 27 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 18 },
        { label: "Obstructed labour", pct: 16 },
        { label: "Malaria in pregnancy", pct: 11 },
        { label: "Other", pct: 7 },
      ],
      context: "Benin introduced free caesarean sections in 2009, improving access but not matched with blood bank investment — haemorrhage remains the top killer.",
      trend: "Modest improvement. The gap between quantity (facility births) and quality (emergency care) is the primary challenge.",
    },
    drivers: [
      "Jihadist violence spreading from Burkina Faso into northern provinces",
      "Gap between facility delivery rate and quality of emergency care",
      "Persistent rural-urban inequality in specialist access",
      "Low female secondary education rate (40%)",
    ],
    sdgNote: "Benin's political stability gives it the best chance in the subregion — but security spillover from the north is a growing threat.",
  },
  mauritania: {
    slug: "mauritania",
    childMortality: {
      headline: "Mauritania's under-5 mortality of 63.4 per 1,000 is shaped by extreme climate vulnerability — it is one of the world's most affected countries by desertification.",
      causes: [
        { label: "Neonatal causes", pct: 27 },
        { label: "Diarrheal disease", pct: 18 },
        { label: "Pneumonia", pct: 16 },
        { label: "Malaria", pct: 14 },
        { label: "Other", pct: 25 },
      ],
      context: "Climate change is expanding the desert and reducing arable land, pushing herder communities into food insecurity. Over 15% of children under five are acutely malnourished.",
      trend: "Moderate improvement but significant vulnerability to climate-driven reversals.",
    },
    maternalMortality: {
      headline: "464 maternal deaths per 100,000 — driven by low skilled birth attendance (69%) and a shortage of blood transfusion capacity to manage haemorrhage.",
      causes: [
        { label: "Haemorrhage", pct: 29 },
        { label: "Eclampsia", pct: 22 },
        { label: "Sepsis", pct: 17 },
        { label: "Obstructed labour", pct: 15 },
        { label: "Anaemia", pct: 10 },
        { label: "Other", pct: 7 },
      ],
      context: "Vast geography with extremely low population density. Nomadic communities in the Sahara have virtually no access to formal health services.",
      trend: "Gradual improvement, but the nomadic and remote population remains largely unreached.",
    },
    drivers: [
      "80% of land is desert or semi-desert",
      "Nomadic populations with no access to health facilities",
      "Chronic food insecurity driven by Sahel drought cycles",
      "Low health worker density outside Nouakchott",
    ],
    sdgNote: "Climate adaptation is inseparable from health progress in Mauritania.",
  },
  cameroon: {
    slug: "cameroon",
    childMortality: {
      headline: "Cameroon's under-5 mortality of 62.5 per 1,000 affects a country battling two simultaneous crises: Boko Haram in the Far North and the Anglophone separatist war in the west.",
      causes: [
        { label: "Malaria", pct: 30 },
        { label: "Neonatal causes", pct: 23 },
        { label: "Diarrhoea", pct: 14 },
        { label: "Pneumonia", pct: 13 },
        { label: "HIV/AIDS", pct: 7 },
        { label: "Other", pct: 13 },
      ],
      context: "The Anglophone crisis (since 2016) has effectively destroyed the health system in the North West and South West regions. Boko Haram raids in the Far North have destroyed dozens of health facilities.",
      trend: "National progress stalled since 2016. Conflict zones are experiencing sharp deterioration.",
    },
    maternalMortality: {
      headline: "438 maternal deaths per 100,000 — the Anglophone regions are experiencing sharply worsening rates as armed groups target health facilities.",
      causes: [
        { label: "Haemorrhage", pct: 28 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 17 },
        { label: "Malaria in pregnancy", pct: 15 },
        { label: "Obstructed labour", pct: 12 },
        { label: "Other", pct: 7 },
      ],
      context: "60% of health facilities in the North West and South West regions have closed. 700,000+ people are internally displaced. Health workers face threats from both government forces and separatist fighters.",
      trend: "Deteriorating in conflict zones; modest improvement elsewhere.",
    },
    drivers: [
      "Anglophone separatist war — 700,000 displaced, 60% of facilities closed",
      "Boko Haram raiding communities in the Far North",
      "3.6% HIV prevalence driving maternal complications",
      "Health workers deliberately targeted by armed groups",
    ],
    sdgNote: "Peace in the Anglophone regions would be transformative for Cameroon's health trajectory.",
  },
  "cote-divoire": {
    slug: "cote-divoire",
    childMortality: {
      headline: "Côte d'Ivoire's under-5 mortality of 61.3 per 1,000 is the legacy of a decade of civil wars (2002–2011) that destroyed health infrastructure.",
      causes: [
        { label: "Malaria", pct: 29 },
        { label: "Neonatal causes", pct: 24 },
        { label: "Diarrhoea", pct: 14 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 20 },
      ],
      context: "Post-war recovery has been uneven. The northern regions (former rebel territory) continue to have significantly worse health indicators.",
      trend: "Meaningful improvement since political stabilisation in 2011.",
    },
    maternalMortality: {
      headline: "480 maternal deaths per 100,000 — despite being one of West Africa's larger economies, historically underinvested in rural health.",
      causes: [
        { label: "Haemorrhage", pct: 27 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 18 },
        { label: "Obstructed labour", pct: 15 },
        { label: "Malaria in pregnancy", pct: 12 },
        { label: "Other", pct: 7 },
      ],
      context: "Cocoa farming communities in the west and north are poorly served by health facilities. Post-war reconciliation has been slow.",
      trend: "Gradual improvement post-2011 peace deal.",
    },
    drivers: [
      "Post-war north-south division — northern regions underserved",
      "Cocoa economy dependency creating rural-urban divide",
      "Significant immigrant worker population with no health access",
    ],
    sdgNote: "Côte d'Ivoire has the economic base to accelerate progress — political commitment to equitable investment is the missing element.",
  },
  "dr-congo": {
    slug: "dr-congo",
    childMortality: {
      headline: "DRC's under-5 mortality of 60.5 per 1,000 — in a country of 100 million — means ~480,000 child deaths per year, second only to Nigeria.",
      causes: [
        { label: "Malaria", pct: 29 },
        { label: "Neonatal causes", pct: 25 },
        { label: "Pneumonia", pct: 14 },
        { label: "Diarrhoea", pct: 13 },
        { label: "Other", pct: 19 },
      ],
      context: "DRC has the world's largest active humanitarian crisis. Over 7 million are internally displaced. Repeated Ebola outbreaks (2018–2020 was the world's second largest) decimated health system trust in the east.",
      trend: "Extremely uneven — western provinces improving while eastern provinces face catastrophic deterioration due to M23 and other armed groups.",
    },
    maternalMortality: {
      headline: "547 maternal deaths per 100,000 — in a country where sexual violence is used as a systematic weapon of war.",
      causes: [
        { label: "Haemorrhage", pct: 30 },
        { label: "Eclampsia", pct: 20 },
        { label: "Sepsis", pct: 17 },
        { label: "Obstructed labour", pct: 14 },
        { label: "Unsafe abortion", pct: 10 },
        { label: "Other", pct: 9 },
      ],
      context: "Sexual violence as a weapon of war has created extraordinary trauma, fistula, and HIV transmission affecting maternal outcomes. MSF runs the world's largest fistula repair programme in DRC.",
      trend: "Eastern DRC deteriorating. Western DRC shows slow improvement.",
    },
    drivers: [
      "World's largest active humanitarian crisis — 7M+ displaced",
      "M23, ADF, and 100+ armed groups operating in the east",
      "Sexual violence as systematic weapon of war",
      "World's second largest Ebola outbreak (2018–2020)",
      "Mineral wealth (coltan, gold) funding armed groups",
    ],
    sdgNote: "Eastern DRC requires a security solution before health SDGs become achievable.",
  },
  liberia: {
    slug: "liberia",
    childMortality: {
      headline: "Liberia's under-5 mortality of 59.4 per 1,000 reflects a country that lost 14 years of development to civil wars then faced the world's worst Ebola outbreak.",
      causes: [
        { label: "Malaria", pct: 30 },
        { label: "Neonatal causes", pct: 24 },
        { label: "Diarrhoea", pct: 15 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 18 },
      ],
      context: "Back-to-back civil wars (1989–2003) killed 10% of the population. When Ebola arrived in 2014, Liberia had just 51 doctors for a population of 4 million.",
      trend: "Meaningful improvement since 2003 peace. Post-Ebola recovery is slow but steady.",
    },
    maternalMortality: {
      headline: "652 maternal deaths per 100,000 — reflecting near-total destruction of the skilled health workforce through war and emigration.",
      causes: [
        { label: "Haemorrhage", pct: 28 },
        { label: "Eclampsia", pct: 22 },
        { label: "Sepsis", pct: 19 },
        { label: "Obstructed labour", pct: 16 },
        { label: "Malaria in pregnancy", pct: 10 },
        { label: "Other", pct: 5 },
      ],
      context: "Brain drain has left Liberia critically short of health professionals. Ebola erased a decade of maternal health progress in 18 months.",
      trend: "Improving post-Ebola but still below 2013 levels in rural areas.",
    },
    drivers: [
      "14 years of civil war destroying health infrastructure",
      "2014 Ebola epidemic with only 51 doctors for 4M people",
      "Severe brain drain of health professionals",
      "Rubber plantation economy with poor worker health coverage",
    ],
    sdgNote: "Sustained investment in health worker training and retention is the critical lever for Liberia.",
  },
  uganda: {
    slug: "uganda",
    childMortality: {
      headline: "Uganda's under-5 mortality of 58.2 per 1,000 is among the better performers in East Africa, but remains far from SDG targets.",
      causes: [
        { label: "Neonatal causes", pct: 27 },
        { label: "Malaria", pct: 26 },
        { label: "Pneumonia", pct: 14 },
        { label: "Diarrhoea", pct: 12 },
        { label: "HIV/AIDS", pct: 6 },
        { label: "Other", pct: 15 },
      ],
      context: "Uganda has been an HIV control success story — prevalence dropped from 18% in the 1990s to ~5% today. The north, affected by the Lord's Resistance Army until 2006, continues to have worse outcomes.",
      trend: "Steady improvement since 2000. Uganda is one of few sub-Saharan countries on a credible path toward SDG targets.",
    },
    maternalMortality: {
      headline: "284 maternal deaths per 100,000 — Uganda's relatively lower rate reflects significant investment in 170,000 community health workers.",
      causes: [
        { label: "Haemorrhage", pct: 26 },
        { label: "Eclampsia", pct: 20 },
        { label: "Sepsis", pct: 17 },
        { label: "Obstructed labour", pct: 15 },
        { label: "HIV in pregnancy", pct: 10 },
        { label: "Other", pct: 12 },
      ],
      context: "Uganda's Village Health Team programme — 170,000 trained community health workers — has been transformative for rural maternal care. However, the anti-homosexuality law (2023) has caused significant aid withdrawal.",
      trend: "Consistent improvement over 20 years. 2023 anti-gay law risks cutting external health funding.",
    },
    drivers: [
      "HIV success story — 5% prevalence still drives maternal deaths",
      "High fertility rate (4.7) creating large absolute burden",
      "2023 anti-homosexuality law causing international aid withdrawal",
      "LRA legacy — northern Uganda still recovering",
    ],
    sdgNote: "Uganda is one of few countries in the region on a credible SDG trajectory, though political decisions risk derailing progress.",
  },
  "equatorial-guinea": {
    slug: "equatorial-guinea",
    childMortality: {
      headline: "Equatorial Guinea's under-5 mortality of 57.3 per 1,000 is a paradox — it has the highest GDP per capita in sub-Saharan Africa yet among the worst health outcomes.",
      causes: [
        { label: "Malaria", pct: 32 },
        { label: "Neonatal causes", pct: 23 },
        { label: "Diarrhoea", pct: 14 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 18 },
      ],
      context: "President Obiang has ruled since 1979. Oil wealth has been systematically looted by the ruling family while children die from preventable malaria.",
      trend: "Despite oil wealth, mortality rates have barely improved in 20 years — a textbook resource curse.",
    },
    maternalMortality: {
      headline: "301 maternal deaths per 100,000 — unconscionably high for Africa's richest country per capita.",
      causes: [
        { label: "Haemorrhage", pct: 27 },
        { label: "Eclampsia", pct: 22 },
        { label: "Sepsis", pct: 18 },
        { label: "Malaria in pregnancy", pct: 16 },
        { label: "Obstructed labour", pct: 11 },
        { label: "Other", pct: 6 },
      ],
      context: "The ruling Obiang family controls all health spending. International NGOs operate under extreme restrictions.",
      trend: "Minimal improvement despite 40+ years of oil production.",
    },
    drivers: [
      "Longest-serving dictator in Africa — Obiang since 1979",
      "Oil wealth systematically looted by ruling family",
      "International NGOs under extreme restrictions",
      "Malaria hyperendemicity in tropical rainforest climate",
    ],
    sdgNote: "Equatorial Guinea's health crisis is entirely a governance crisis — it has the financial resources to be a health leader in Africa.",
  },
  tanzania: {
    slug: "tanzania",
    childMortality: {
      headline: "Tanzania's under-5 mortality of 55.8 per 1,000 reflects meaningful progress in serving a rapidly growing population of 65 million.",
      causes: [
        { label: "Neonatal causes", pct: 27 },
        { label: "Malaria", pct: 25 },
        { label: "Pneumonia", pct: 14 },
        { label: "Diarrhoea", pct: 12 },
        { label: "HIV/AIDS", pct: 5 },
        { label: "Other", pct: 17 },
      ],
      context: "Tanzania is politically stable and has made consistent health investments, including early adoption of bed net programmes. COVID-19 denialism under President Magufuli set back pandemic preparedness.",
      trend: "Consistent improvement since 2000 — child mortality has halved. Current president has restored international health partnerships.",
    },
    maternalMortality: {
      headline: "349 maternal deaths per 100,000 — Tanzania's stable governance and consistent health investment have driven meaningful improvements.",
      causes: [
        { label: "Haemorrhage", pct: 25 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 17 },
        { label: "Malaria in pregnancy", pct: 15 },
        { label: "Obstructed labour", pct: 13 },
        { label: "Other", pct: 9 },
      ],
      context: "Tanzania's Big Results Now (BRN) health initiative significantly improved facility delivery rates. Zanzibar has better maternal outcomes than the mainland.",
      trend: "Steady improvement. Tanzania is one of the more credible SDG progress stories in the region.",
    },
    drivers: [
      "COVID denialism under Magufuli (2020–2021) disrupting health systems",
      "Rapid population growth (65M, growing 3% annually)",
      "High malaria burden in lake regions",
      "High adolescent pregnancy rate (27%)",
    ],
    sdgNote: "Tanzania is among the most likely countries in sub-Saharan Africa to achieve meaningful SDG 3 progress by 2030.",
  },
  "rep-of-congo": {
    slug: "rep-of-congo",
    childMortality: {
      headline: "The Republic of Congo's under-5 mortality of 54.9 per 1,000 reflects a country where oil wealth has not translated into health improvements.",
      causes: [
        { label: "Malaria", pct: 27 },
        { label: "Neonatal causes", pct: 25 },
        { label: "Diarrhoea", pct: 15 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 20 },
      ],
      context: "President Sassou Nguesso has ruled for 38+ years in a system of patronage and elite capture of oil revenues.",
      trend: "Moderate improvement since 2000 but far below potential given economic resources.",
    },
    maternalMortality: {
      headline: "378 maternal deaths per 100,000 — despite being an oil exporter, health infrastructure outside Brazzaville and Pointe-Noire is severely underdeveloped.",
      causes: [
        { label: "Haemorrhage", pct: 27 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 18 },
        { label: "Obstructed labour", pct: 16 },
        { label: "Malaria in pregnancy", pct: 11 },
        { label: "Other", pct: 7 },
      ],
      context: "Rainforest geography makes rural access extremely difficult. Brain drain of health professionals to France is significant.",
      trend: "Gradual improvement but below the pace of oil revenue growth.",
    },
    drivers: [
      "Oil revenues captured by Sassou Nguesso patronage system",
      "Rainforest geography isolating rural communities",
      "Brain drain of health professionals to France",
    ],
    sdgNote: "Governance reform would be the single most impactful intervention for health in Republic of Congo.",
  },
  ethiopia: {
    slug: "ethiopia",
    childMortality: {
      headline: "Ethiopia's under-5 mortality of 53.6 per 1,000 — in Africa's second most populous country (125M) — means ~400,000 Ethiopian children die annually.",
      causes: [
        { label: "Neonatal causes", pct: 30 },
        { label: "Pneumonia", pct: 17 },
        { label: "Diarrhoea", pct: 14 },
        { label: "Malaria", pct: 12 },
        { label: "Other", pct: 27 },
      ],
      context: "Ethiopia was a global health success story 2000–2015 through its Health Extension Program — 45,000 female community health workers deployed to rural villages. The Tigray War (2020–2022) dramatically reversed gains in conflict-affected regions.",
      trend: "Nationally significant improvement since 2000. Tigray war caused one of the worst humanitarian disasters in recent history.",
    },
    maternalMortality: {
      headline: "267 maternal deaths per 100,000 — Ethiopia's Health Extension Program has been one of the most successful maternal health initiatives in Africa.",
      causes: [
        { label: "Haemorrhage", pct: 25 },
        { label: "Eclampsia", pct: 20 },
        { label: "Sepsis", pct: 17 },
        { label: "Obstructed labour", pct: 15 },
        { label: "Malaria in pregnancy", pct: 10 },
        { label: "Other", pct: 13 },
      ],
      context: "The Tigray War systematically targeted health facilities — over 70% of Tigray's health facilities were damaged or destroyed. An estimated 100,000+ people died in the conflict.",
      trend: "Strong national improvement trajectory, severely disrupted by Tigray and subsequent conflicts.",
    },
    drivers: [
      "Tigray War (2020–2022) — systematic destruction of health facilities",
      "Ongoing Amhara and Oromia conflicts displacing millions",
      "45,000 Health Extension Workers — Africa's most successful CHW programme",
      "Recurring drought and food crisis affecting 45% of children",
    ],
    sdgNote: "Ethiopia's HEP model shows what community health investment can achieve. Sustaining peace is now the critical prerequisite.",
  },
  madagascar: {
    slug: "madagascar",
    childMortality: {
      headline: "Madagascar's under-5 mortality of 52.5 per 1,000 reflects a country where 80% of the population lives below $2/day and 50% of children are chronically malnourished.",
      causes: [
        { label: "Neonatal causes", pct: 28 },
        { label: "Diarrhoea", pct: 20 },
        { label: "Pneumonia", pct: 16 },
        { label: "Malaria", pct: 10 },
        { label: "Other", pct: 26 },
      ],
      context: "Madagascar has the world's highest stunting rate (~50%). The 2009 political crisis caused years of aid suspension. Cyclone seasons cause regular humanitarian emergencies. The Grand Sud region regularly experiences famine.",
      trend: "Modest overall improvement but deeply uneven — the Grand Sud faces periodic famine conditions.",
    },
    maternalMortality: {
      headline: "335 maternal deaths per 100,000 — heavily driven by malnutrition and anaemia in pregnancy, and a critical shortage of health professionals (0.18 doctors per 1,000).",
      causes: [
        { label: "Haemorrhage", pct: 28 },
        { label: "Anaemia / malnutrition", pct: 22 },
        { label: "Eclampsia", pct: 18 },
        { label: "Sepsis", pct: 16 },
        { label: "Obstructed labour", pct: 10 },
        { label: "Other", pct: 6 },
      ],
      context: "The 2009 coup led to suspension of international aid for years. Annual cyclone seasons destroy infrastructure. Southern region Grand Sud regularly faces drought-driven famine.",
      trend: "Limited progress. Political instability and climate vulnerability create persistent setbacks.",
    },
    drivers: [
      "World's highest stunting rate — 50% of children chronically malnourished",
      "Grand Sud region recurring famine",
      "2009 political crisis causing prolonged aid suspension",
      "Annual cyclone seasons destroying infrastructure",
      "0.18 doctors per 1,000 people",
    ],
    sdgNote: "Madagascar requires sustained political stability and climate resilience investment alongside health system strengthening.",
  },
  malawi: {
    slug: "malawi",
    childMortality: {
      headline: "Malawi's under-5 mortality of 51.4 per 1,000 reflects a densely populated, landlocked country with few natural resources but relatively strong governance.",
      causes: [
        { label: "Neonatal causes", pct: 29 },
        { label: "Malaria", pct: 23 },
        { label: "Pneumonia", pct: 15 },
        { label: "Diarrhoea", pct: 12 },
        { label: "HIV/AIDS", pct: 7 },
        { label: "Other", pct: 14 },
      ],
      context: "Cyclone Freddy (2023) — the longest-lasting tropical cyclone ever recorded — killed 1,000+ and destroyed health facilities in the south.",
      trend: "Significant improvement since 2000 — mortality has halved. Malawi punches above its weight relative to its GDP.",
    },
    maternalMortality: {
      headline: "349 maternal deaths per 100,000 — Malawi has made progress through a community midwifery programme and investment in emergency obstetric care.",
      causes: [
        { label: "Haemorrhage", pct: 26 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 17 },
        { label: "Malaria in pregnancy", pct: 15 },
        { label: "HIV in pregnancy", pct: 10 },
        { label: "Other", pct: 11 },
      ],
      context: "Malawi pioneered clinical officers performing caesarean sections — a WHO-recognised innovation expanding emergency obstetric care where doctors are absent. HIV prevalence (9%) remains a significant driver of maternal deaths.",
      trend: "Meaningful improvement. Malawi's clinical officer model is being replicated across the region.",
    },
    drivers: [
      "Cyclone Freddy (2023) — deadliest cyclone in African history",
      "9% HIV prevalence — driving maternal and child deaths",
      "Innovative clinical officer C-section programme — a regional model",
      "Aid dependence — external funding covers 50%+ of health budget",
    ],
    sdgNote: "Malawi is one of sub-Saharan Africa's more credible SDG progress stories given its resource constraints.",
  },
  sudan: {
    slug: "sudan",
    childMortality: {
      headline: "Sudan's under-5 mortality of 50.3 per 1,000 was improving until the April 2023 war created the world's largest displacement crisis.",
      causes: [
        { label: "Neonatal causes", pct: 28 },
        { label: "Malaria", pct: 22 },
        { label: "Diarrhoea", pct: 15 },
        { label: "Pneumonia", pct: 13 },
        { label: "Other", pct: 22 },
      ],
      context: "The 2023 war has displaced over 8 million people and collapsed Sudan's health system. As of 2024, 70–80% of health facilities in conflict areas are non-functional. The RSF is committing mass atrocities in Darfur.",
      trend: "Was improving 2000–2022. The 2023 war has caused catastrophic reversal.",
    },
    maternalMortality: {
      headline: "276 maternal deaths per 100,000 — but the 2023 war has caused this to worsen dramatically in conflict-affected states.",
      causes: [
        { label: "Haemorrhage", pct: 27 },
        { label: "Eclampsia", pct: 21 },
        { label: "Sepsis", pct: 17 },
        { label: "Malaria in pregnancy", pct: 15 },
        { label: "Obstructed labour", pct: 13 },
        { label: "Other", pct: 7 },
      ],
      context: "Hospitals in Khartoum and Darfur have been systematically attacked. Cholera, malaria, and measles are spreading rapidly among displaced populations. MSF has documented RSF fighters using hospitals as military bases.",
      trend: "Rapidly deteriorating since April 2023.",
    },
    drivers: [
      "SAF-RSF civil war (April 2023) — world's largest displacement crisis (8M+)",
      "80% of health facilities non-functional in conflict zones",
      "Cholera and measles epidemics spreading among displaced populations",
      "RSF committing mass atrocities in Darfur",
      "Hospitals deliberately targeted and occupied",
    ],
    sdgNote: "Sudan's 2023 war represents one of the fastest reversals of health progress in modern history. Peace is the only prerequisite.",
  },
  haiti: {
    slug: "haiti",
    childMortality: {
      headline: "Haiti's under-5 mortality of 49.7 per 1,000 is the highest in the Western Hemisphere — in a country that has not had a functioning government since President Moïse's assassination in 2021.",
      causes: [
        { label: "Neonatal causes", pct: 27 },
        { label: "Diarrhoea", pct: 20 },
        { label: "Pneumonia", pct: 14 },
        { label: "Cholera", pct: 8 },
        { label: "Other", pct: 31 },
      ],
      context: "Haiti is the only country in the Americas where cholera has returned (reintroduced 2022). Gangs control 80% of Port-au-Prince. The 2010 earthquake killed 230,000; the 2021 earthquake killed 2,000+.",
      trend: "No meaningful improvement in a decade. Conditions are worsening due to gang violence and state collapse.",
    },
    maternalMortality: {
      headline: "480 maternal deaths per 100,000 — the highest in the Americas, in a country where gangs control access to the main hospital.",
      causes: [
        { label: "Haemorrhage", pct: 28 },
        { label: "Eclampsia", pct: 22 },
        { label: "Sepsis", pct: 17 },
        { label: "Obstructed labour", pct: 15 },
        { label: "Unsafe abortion", pct: 10 },
        { label: "Other", pct: 8 },
      ],
      context: "Gang control of Port-au-Prince has made the main referral hospital effectively inaccessible. 45% of children are acutely malnourished. PAHO warns of imminent collapse of the entire health system.",
      trend: "Rapidly deteriorating since 2021.",
    },
    drivers: [
      "Gang control of 80%+ of Port-au-Prince",
      "Presidential assassination (2021) — no functional government since",
      "Cholera epidemic (reintroduced 2022) by UN peacekeepers",
      "2010 + 2021 earthquakes — cumulative devastation",
      "45% of children acutely malnourished",
    ],
    sdgNote: "Haiti is the only country in the Western Hemisphere with sub-Saharan Africa–level mortality rates. Emergency international intervention is required.",
  },
};

export function getAnalysisBySlug(slug: string): CountryAnalysis | null {
  return ANALYSIS[slug] ?? null;
}
